@hostname = localhost
@port = 3000
@root = http://{{hostname}}:{{port}}/api
# Replace token below with your user's token
# @token = AbCdEfGhIjKlMnOpQrStUvWx

### front
GET {{root}}/front
	?page%5Bnumber%5D=1
	&page%5Bsize%5D=10

### poll
GET {{root}}/poll

### search
GET {{root}}/search
Content-Type: application/json

{
	"page": {
		"number": 1,
		"size": 10
	},
	"s": "democrat",
	"tags": ["bernie sanders", "us news"]
}

### test post
POST {{root}}/test
Content-Type: application/json

{
	"key1": "value1",
	"key2": "value2",
	"key3": "value3"
}

### test get
GET {{root}}/test

### version
GET {{root}}/

### oauth
GET http://{{hostname}}:{{port}}/auth/google_oauth2

### [Fake] Auth
GET {{root}}/auth
Content-Type: application/json

{
	"name": "Bobby McTest",
	"email": "bobby@test.io"
}

### Get Me
GET {{root}}/me
Authorization: {{token}}

### Update Me
PUT {{root}}/me
Content-Type: application/json
Authorization: {{token}}

{
	"name": "Bobby McTest",
	"email": "bobby@test.io"
}

### Create Feed
POST {{root}}/feed
Content-Type: application/json
Authorization: {{token}}

{
	"name": "Companies",
	"query": "snapchat"
}

### Destroy Feed
DELETE {{root}}/feed/1
Authorization: {{token}}
